import psi4
import torch
import numpy as np
from ad_btensor import autodiff_Btensor
from ad_btensor import fast_B
import ad_intcos
import time
torch.set_printoptions(precision=5)
bohr2ang = 0.529177249
psi4.core.be_quiet()

def test_molecule(psi_geom,ad_intcoords):
    """ 
    Tests fast autodiff-OptKing versus slow autodiff-Optking 

    Parameters: 
    ---------
    psi_geom : Psi4 Matrix,Molecule.geometry(),
    ad_intcoords : list of new autodiff optking internal coordinates objects STRE,BEND,TORS
    """
    npgeom = np.array(psi_geom) * bohr2ang
    geom1 = torch.tensor(npgeom,requires_grad=True)
    autodiff_coords = ad_intcos.qValues(ad_intcoords,geom1)
    B1 = autodiff_Btensor(ad_intcoords,geom1,order=1)
    B2 = autodiff_Btensor(ad_intcoords,geom1,order=2)

    geom2 = torch.tensor(npgeom,requires_grad=False)
    B1_fast, B2_fast = fast_B(ad_intcoords, geom2)
    print('Same B-Matrix...',torch.allclose(B1,B1_fast))
    print('Same 2nd order B-Matrix...',torch.allclose(B2,B2_fast))


    #optking_coords = optking.intcosMisc.qValues(optking_intcoords,npgeom)
    #B2 = optking.intcosMisc.Bmat(optking_intcoords,npgeom)
    #c = time.time()

    ## Test 2nd order B tensor. Can only do one coord at a time in OPTKING.
    ## Must modify optking.testB.testDerivativeB to return it in testDerivativeB()
    #A = time.time()
    #B3 = autodiff_Btensor(ad_intcoords,geom,order=2)
    #B = time.time()
    #junk, B4 = optking.testB.testDerivativeB(optking_intcoords, npgeom) 
    #C = time.time()

    #print('Same Internal Coordinates...',torch.allclose(autodiff_coords,torch.tensor(optking_coords)), end=' ')
    #print('Same B-Matrix...',torch.allclose(B1,torch.tensor(B2)), end=' ')
    #print('Same Second Order B-Tensor...',torch.allclose(B3[-1],torch.tensor(B4)))

    ##print("AutoDiff Optking took {} seconds".format(round((b-a), 2)))
    ##print("Optking took {} seconds".format(round((c-b), 2)))
    #print("AutoDiff Optking took {} seconds".format(round((B-A) + (b-a), 2)))
    #print("Optking took {} seconds".format(round((C-B) + (c-b), 2)))

h2o = psi4.geometry(
'''
H            0.000000000000     0.000000000000     0.950000000000 
H            0.000000000000     0.872305301500    -0.376275777700 
O            0.000000000000     0.000000000000     0.000000000000 
''')
linear_h2o = psi4.geometry(
'''
H            0.000000000000     0.000000000000     1.950000000000 
H            0.000000000000     0.000000000000     0.050000000000 
O            0.000000000000     0.000000000000     1.000000000000 
''')
ammonia = psi4.geometry(
'''
 N  0.000000  0.0       0.0 
 H  1.584222  0.0       1.12022
 H  0.0      -1.58422  -1.12022
 H -1.584222  0.0       1.12022
 H  0.0       1.58422  -1.12022
 unit au
''')
h2co = psi4.geometry(
'''
C            0.000000000000     0.000000000000    -0.607835855018 
O            0.000000000000     0.000000000000     0.608048883261 
H            0.000000000000     0.942350938995    -1.206389817026 
H            0.000000000000    -0.942350938995    -1.206389817026 
''')
bent_h2co = psi4.geometry(# h2co,but 160 degree dihedral
'''
C            0.011014420656    -0.636416764906     0.000000000000 
O            0.011014420656     0.628402205849     0.000000000000 
H           -0.152976834267    -1.197746817763     0.930040622624 
H           -0.152976834267    -1.197746817763    -0.930040622624 
''')
hooh = psi4.geometry(
'''
H
O 1 0.9
O 2 1.4 1 100.0
H 3 0.9 2 100.0 1 114.0
''')
sf4 = psi4.geometry(
'''
 S  0.00000000  -0.00000000  -0.30618267
 F -1.50688420  -0.00000000   0.56381732
 F  0.00000000  -1.74000000  -0.30618267
 F -0.00000000   1.74000000  -0.30618267
 F  1.50688420   0.00000000   0.56381732
''')
# Use intcos_generate_exit autogenerated internal coordinates for a few big molecules
allene = psi4.geometry(
"""
H  0.0  -0.92   -1.8
H  0.0   0.92   -1.8
C  0.0   0.00   -1.3
C  0.0   0.00    0.0
C  0.0   0.00    1.3
H  0.92  0.00    1.8
H -0.92  0.00    1.8
""")
big = psi4.geometry( 
'''
 C  0.00000000 0.00000000 0.00000000
 Cl 0.19771002 -0.99671665 -1.43703398
 C  1.06037767 1.11678073 0.00000000
 C  2.55772698 0.75685710 0.00000000
 H  3.15117939 1.67114056 0.00000000
 H  2.79090687 0.17233980 0.88998127
 H  2.79090687 0.17233980 -0.88998127
 H  0.75109254 2.16198057 0.00000000
 H -0.99541786 0.44412079 0.00000000
 H  0.12244541 -0.61728474 0.88998127
'''
)

h2o_autodiff = [ad_intcos.STRE(2,1),ad_intcos.STRE(2,0),ad_intcos.BEND(1,2,0)]

linear_h2o_autodiff = [ad_intcos.STRE(2,1),ad_intcos.STRE(2,0),ad_intcos.BEND(1,2,0,bendType='LINEAR')]

ammonia_autodiff = [ad_intcos.STRE(0,1),ad_intcos.STRE(0,2),ad_intcos.STRE(0,3),ad_intcos.STRE(0,4),ad_intcos.BEND(1,0,2),ad_intcos.BEND(1,0,3),ad_intcos.BEND(1,0,4),ad_intcos.BEND(2,0,3), ad_intcos.BEND(2,0,4),ad_intcos.BEND(3,0,4)]

h2co_autodiff = [ad_intcos.STRE(0,1),ad_intcos.STRE(0,2),ad_intcos.BEND(2,0,1),ad_intcos.STRE(0,3),ad_intcos.BEND(3,0,1),ad_intcos.TORS(3,0,1,2)]

hooh_autodiff = [ad_intcos.STRE(0,1),ad_intcos.STRE(0,2),ad_intcos.BEND(2,1,0),ad_intcos.STRE(3,2),ad_intcos.BEND(3,2,1),ad_intcos.TORS(3,2,1,0)]

sf4_autodiff = [ad_intcos.TORS(0,1,2,3),ad_intcos.TORS(1,3,4,0),ad_intcos.TORS(0,2,1,4)]

allene_autodiff = [ad_intcos.STRE(0, 2),ad_intcos.STRE(1, 2),ad_intcos.STRE(2, 3),ad_intcos.STRE(3, 4),ad_intcos.STRE(4, 5),ad_intcos.STRE(4, 6),ad_intcos.BEND(0, 2, 1),ad_intcos.BEND(0, 2, 3),ad_intcos.BEND(1, 2, 3),ad_intcos.BEND(2, 3, 4),ad_intcos.BEND(2, 3, 4),ad_intcos.BEND(3, 4, 5),ad_intcos.BEND(3, 4, 6),ad_intcos.BEND(5, 4, 6),ad_intcos.TORS(0, 2, 4, 5),ad_intcos.TORS(0, 2, 4, 6),ad_intcos.TORS(1, 2, 4, 5),ad_intcos.TORS(1, 2, 4, 6)]

big_autodiff = [ad_intcos.STRE(0, 1),ad_intcos.STRE(0, 2),ad_intcos.STRE(0, 8),ad_intcos.STRE(0, 9),ad_intcos.STRE(2, 3),ad_intcos.STRE(2, 7),ad_intcos.STRE(3, 4),ad_intcos.STRE(3, 5),ad_intcos.STRE(3, 6),ad_intcos.BEND(0, 2, 3),ad_intcos.BEND(0, 2, 7),ad_intcos.BEND(1, 0, 2),ad_intcos.BEND(1, 0, 8),ad_intcos.BEND(1, 0, 9),ad_intcos.BEND(2, 0, 8),ad_intcos.BEND(2, 0, 9),ad_intcos.BEND(2, 3, 4),ad_intcos.BEND(2, 3, 5),ad_intcos.BEND(2, 3, 6),ad_intcos.BEND(3, 2, 7),ad_intcos.BEND(4, 3, 5),ad_intcos.BEND(4, 3, 6),ad_intcos.BEND(5, 3, 6),ad_intcos.BEND(8, 0, 9),ad_intcos.TORS(0, 2, 3, 4),ad_intcos.TORS(0, 2, 3, 5),ad_intcos.TORS(0, 2, 3, 6),ad_intcos.TORS(1, 0, 2, 3),ad_intcos.TORS(1, 0, 2, 7),ad_intcos.TORS(3, 2, 0, 8),ad_intcos.TORS(3, 2, 0, 9),ad_intcos.TORS(4, 3, 2, 7),ad_intcos.TORS(5, 3, 2, 7),ad_intcos.TORS(6, 3, 2, 7),ad_intcos.TORS(7, 2, 0, 8),ad_intcos.TORS(7, 2, 0, 9)]

print("Testing water...")
test_molecule(h2o.geometry(),h2o_autodiff)
print("Testing linear water...")
test_molecule(linear_h2o.geometry(),linear_h2o_autodiff)
print("Testing ammonia...")
test_molecule(ammonia.geometry(),ammonia_autodiff)
print("Testing formaldehyde...")
test_molecule(h2co.geometry(),h2co_autodiff)
print("Testing bent formaldehyde...")
test_molecule(bent_h2co.geometry(),h2co_autodiff)
print("Testing hooh...")
test_molecule(hooh.geometry(),hooh_autodiff)
print("Testing nonsense sf4 ...")
test_molecule(sf4.geometry(),sf4_autodiff)
print("Testing allene...")
test_molecule(allene.geometry(),allene_autodiff)
print("Testing ch3chch2cl...")
test_molecule(big.geometry(),big_autodiff)




